---
# Playbook to collect Network Facts from multiple vendors.
- hosts: datacenter
  connection: local
  tasks:
    - name: "Collect Facts from Arista EOS switches"
      eos_facts:
        provider: "{{ eoscli }}"
        gather_subset:
          - all
      when: ansible_nos == "eos"
      register: result


    - name: "Collect Facts from JunOS  switches"
      junos_facts:
        provider: "{{ junosnetconf }}"
        gather_subset:
          - all
      when: ansible_nos == "junos"
      register: result

    - name: "Collect Facts from IOSXR switches"
      junos_facts:
        provider: "{{ iosxrcli }}"
        gather_subset:
           - all
      when: ansible_nos == "iosxr"
      register: result
