---
# tasks to collect all dell os interface facts
- hosts: datacenter
  connection: local
  tasks:
    - name: "Collect Facts from Dell OS10 switches"
      dellos10_facts:
        provider: "{{ cli }}"
        gather_subset:
             - all
      register: facts


