---
hostname: leaf4
cli:
  host: "{{ ansible_host }}"
  username: "{{ dellos_cli_user | default('admin') }}"
  password: "{{ dellos_cli_pass | default('admin123') }}"
  authorize: true
  auth_pass: "{{ dellos_cli_auth_pass | default('force10os6') }}"
  transport: cli
